### ISSUE TITLE
8 bit = 256

### ISSUE THREAD

**Issue by brean** [TheThinMatrix/LowPolyTerrain#1]
Hi,

Maybe I am wrong but to convert colors shouldn't this be 256 instead of 255? 
https://github.com/TheThinMatrix/LowPolyTerrain/blob/c8a8f75101c58f4a50e550751ab3af610ef3aa87/OpenGlWrapper/utils/Colour.java#L28

**Comment by TheThinMatrix** [comment]
8 bits gives 256 possible values, which gives us numbers from 0 to 255. The highest possible value for a colour is therefore 255 which is why 255 is used here.
